apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-hello-world 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: f5-hello-world
    spec:
      containers:
      - name: f5-hello-world
        image: "f5devcentral/f5-hello-world"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
